const localCodeNames: Array<{ localCode: string; name: string }> = [
  { localCode: "ab", name: "Abkhazian" },
  { localCode: "ace", name: "Achinese" },
  { localCode: "ach", name: "Acoli" },
  { localCode: "af", name: "Afrikaans" },
  { localCode: "ak", name: "Akan" },
  { localCode: "alz", name: "Alur" },
  { localCode: "am", name: "Amharic" },
  { localCode: "ar", name: "Arabic" },
  { localCode: "as", name: "Assamese" },
  { localCode: "awa", name: "Awadhi" },
  { localCode: "ay", name: "Aymara" },
  { localCode: "az", name: "Azerbaijani" },
  { localCode: "ba", name: "Bashkir" },
  { localCode: "ban", name: "Balinese" },
  { localCode: "bbc", name: "Batak Toba" },
  { localCode: "be", name: "Belarusian" },
  { localCode: "bem", name: "Bemba" },
  { localCode: "bew", name: "Betawi" },
  { localCode: "bg", name: "Bulgarian" },
  { localCode: "bho", name: "Bhojpuri" },
  { localCode: "bik", name: "Bikol" },
  { localCode: "bm", name: "Bambara" },
  { localCode: "bn", name: "Bengali" },
  { localCode: "br", name: "Breton" },
  { localCode: "bs", name: "Bosnian" },
  { localCode: "bts", name: "Batak Simalungun" },
  { localCode: "btx", name: "Batak Karo" },
  { localCode: "bua", name: "Buriat" },
  { localCode: "ca", name: "Catalan" },
  { localCode: "ceb", name: "Cebuano" },
  { localCode: "cgg", name: "Chiga" },
  { localCode: "chm", name: "Mari" },
  { localCode: "ckb", name: "Central Kurdish" },
  { localCode: "cnh", name: "Haka Chin" },
  { localCode: "co", name: "Corsican" },
  { localCode: "crh", name: "Crimean Tatar" },
  { localCode: "crs", name: "Seselwa Creole French" },
  { localCode: "cs", name: "Czech" },
  { localCode: "cv", name: "Chuvash" },
  { localCode: "cy", name: "Welsh" },
  { localCode: "da", name: "Danish" },
  { localCode: "de", name: "German" },
  { localCode: "din", name: "Dinka" },
  { localCode: "doi", name: "Dogri" },
  { localCode: "dov", name: "Dombe" },
  { localCode: "dv", name: "Dhivehi" },
  { localCode: "dz", name: "Dzongkha" },
  { localCode: "ee", name: "Ewe" },
  { localCode: "el", name: "Modern Greek" },
  { localCode: "en", name: "English" },
  { localCode: "eo", name: "Esperanto" },
  { localCode: "es", name: "Spanish" },
  { localCode: "et", name: "Estonian" },
  { localCode: "eu", name: "Basque" },
  { localCode: "fa", name: "Persian" },
  { localCode: "ff", name: "Fulah" },
  { localCode: "fi", name: "Finnish" },
  { localCode: "fj", name: "Fijian" },
  { localCode: "fr", name: "French" },
  { localCode: "fr-CA", name: "French (Canada)" },
  { localCode: "fy", name: "Western Frisian" },
  { localCode: "ga", name: "Irish" },
  { localCode: "gaa", name: "Ga" },
  { localCode: "gd", name: "Scottish Gaelic" },
  { localCode: "gl", name: "Galician" },
  { localCode: "gn", name: "Guarani" },
  { localCode: "gom", name: "Goan Konkani" },
  { localCode: "gu", name: "Gujarati" },
  { localCode: "ha", name: "Hausa" },
  { localCode: "haw", name: "Hawaiian" },
  { localCode: "he", name: "Hebrew" },
  { localCode: "hi", name: "Hindi" },
  { localCode: "hil", name: "Hiligaynon" },
  { localCode: "hmn", name: "Hmong" },
  { localCode: "hr", name: "Croatian" },
  { localCode: "hrx", name: "Hunsrik" },
  { localCode: "ht", name: "Haitian" },
  { localCode: "hu", name: "Hungarian" },
  { localCode: "hy", name: "Armenian" },
  { localCode: "id", name: "Indonesian" },
  { localCode: "ig", name: "Igbo" },
  { localCode: "ilo", name: "Iloko" },
  { localCode: "is", name: "Icelandic" },
  { localCode: "it", name: "Italian" },
  { localCode: "iw", name: "Hebrew" },
  { localCode: "ja", name: "Japanese" },
  { localCode: "jv", name: "Javanese" },
  { localCode: "jw", name: "Javanese" },
  { localCode: "ka", name: "Georgian" },
  { localCode: "kk", name: "Kazakh" },
  { localCode: "km", name: "Central Khmer" },
  { localCode: "kn", name: "Kannada" },
  { localCode: "ko", name: "Korean" },
  { localCode: "kri", name: "Krio" },
  { localCode: "ktu", name: "Kituba (Democratic Republic of Congo)" },
  { localCode: "ku", name: "Kurdish" },
  { localCode: "ky", name: "Kirghiz" },
  { localCode: "la", name: "Latin" },
  { localCode: "lb", name: "Luxembourgish" },
  { localCode: "lg", name: "Ganda" },
  { localCode: "li", name: "Limburgan" },
  { localCode: "lij", name: "Ligurian" },
  { localCode: "lmo", name: "Lombard" },
  { localCode: "ln", name: "Lingala" },
  { localCode: "lo", name: "Lao" },
  { localCode: "lt", name: "Lithuanian" },
  { localCode: "ltg", name: "Latgalian" },
  { localCode: "luo", name: "Luo" },
  { localCode: "lus", name: "Lushai" },
  { localCode: "lv", name: "Latvian" },
  { localCode: "mai", name: "Maithili" },
  { localCode: "mak", name: "Makasar" },
  { localCode: "mg", name: "Malagasy" },
  { localCode: "mi", name: "Maori" },
  { localCode: "min", name: "Minangkabau" },
  { localCode: "mk", name: "Macedonian" },
  { localCode: "ml", name: "Malayalam" },
  { localCode: "mn", name: "Mongolian" },
  { localCode: "mni-Mtei", name: "Meitei" },
  { localCode: "mr", name: "Marathi" },
  { localCode: "ms", name: "Malay" },
  { localCode: "ms-Arab", name: "Malay (Arabic)" },
  { localCode: "mt", name: "Maltese" },
  { localCode: "my", name: "Burmese" },
  { localCode: "ne", name: "Nepali" },
  { localCode: "new", name: "Newari" },
  { localCode: "nl", name: "Dutch" },
  { localCode: "no", name: "Norwegian" },
  { localCode: "nr", name: "South Ndebele" },
  { localCode: "nso", name: "Pedi" },
  { localCode: "nus", name: "Nuer" },
  { localCode: "ny", name: "Nyanja" },
  { localCode: "oc", name: "Occitan" },
  { localCode: "om", name: "Oromo" },
  { localCode: "or", name: "Oriya" },
  { localCode: "pa", name: "Panjabi" },
  { localCode: "pa-Arab", name: "Panjabi (Arabic)" },
  { localCode: "pag", name: "Pangasinan" },
  { localCode: "pam", name: "Pampanga" },
  { localCode: "pap", name: "Papiamento" },
  { localCode: "pl", name: "Polish" },
  { localCode: "ps", name: "Pushto" },
  { localCode: "pt", name: "Portuguese" },
  { localCode: "pt-PT", name: "Portuguese (Portugal)" },
  { localCode: "qu", name: "Quechua" },
  { localCode: "rn", name: "Rundi" },
  { localCode: "ro", name: "Romanian" },
  { localCode: "rom", name: "Romany" },
  { localCode: "ru", name: "Russian" },
  { localCode: "rw", name: "Kinyarwanda" },
  { localCode: "sa", name: "Sanskrit" },
  { localCode: "scn", name: "Sicilian" },
  { localCode: "sd", name: "Sindhi" },
  { localCode: "sg", name: "Sango" },
  { localCode: "shn", name: "Shan" },
  { localCode: "si", name: "Sinhala" },
  { localCode: "sk", name: "Slovak" },
  { localCode: "sl", name: "Slovenian" },
  { localCode: "sm", name: "Samoan" },
  { localCode: "sn", name: "Shona" },
  { localCode: "so", name: "Somali" },
  { localCode: "sq", name: "Albanian" },
  { localCode: "sr", name: "Serbian" },
  { localCode: "ss", name: "Swati" },
  { localCode: "st", name: "Southern Sotho" },
  { localCode: "su", name: "Sundanese" },
  { localCode: "sv", name: "Swedish" },
  { localCode: "sw", name: "Swahili" },
  { localCode: "szl", name: "Silesian" },
  { localCode: "ta", name: "Tamil" },
  { localCode: "te", name: "Telugu" },
  { localCode: "tet", name: "Tetum" },
  { localCode: "tg", name: "Tajik" },
  { localCode: "th", name: "Thai" },
  { localCode: "ti", name: "Tigrinya" },
  { localCode: "tk", name: "Turkmen" },
  { localCode: "tl", name: "Tagalog" },
  { localCode: "tn", name: "Tswana" },
  { localCode: "tr", name: "Turkish" },
  { localCode: "ts", name: "Tsonga" },
  { localCode: "tt", name: "Tatar" },
  { localCode: "ug", name: "Uighur" },
  { localCode: "uk", name: "Ukrainian" },
  { localCode: "ur", name: "Urdu" },
  { localCode: "uz", name: "Uzbek" },
  { localCode: "vi", name: "Vietnamese" },
  { localCode: "xh", name: "Xhosa" },
  { localCode: "yi", name: "Yiddish" },
  { localCode: "yo", name: "Yoruba" },
  { localCode: "yua", name: "Yucatec Maya" },
  { localCode: "yue", name: "Yue Chinese" },
  { localCode: "zh", name: "Chinese" },
  { localCode: "zh-CN", name: "Chinese (Simplified)" },
  { localCode: "zh-TW", name: "Chinese (Traditional)" },
  { localCode: "zu", name: "Zulu" },
];

const localCodeLangMapping: Array<{localCode: string; lang: string}> = [
  { localCode: "zh-CN", lang: "zh-Hans" },
  { localCode: "zh-TW", lang: "zh-Hant" },
];

export default localCodeNames;
export { localCodeLangMapping };
