import type LangCodeRecord from "./LangCodeRecord"

export const commonLangs: Array<LangCodeRecord> = [
  { lang: "ab", name: "Abkhazian" },
  { lang: "ace", name: "Achinese" },
  { lang: "ach", name: "Acoli" },
  { lang: "af", name: "Afrikaans" },
  { lang: "ak", name: "Akan" },
  { lang: "alz", name: "Alur" },
  { lang: "am", name: "Amharic" },
  { lang: "ar", name: "Arabic" },
  { lang: "as", name: "Assamese" },
  { lang: "awa", name: "Awadhi" },
  { lang: "ay", name: "Aymara" },
  { lang: "az", name: "Azerbaijani" },
  { lang: "ba", name: "Bashkir" },
  { lang: "ban", name: "Balinese" },
  { lang: "bbc", name: "Batak Toba" },
  { lang: "be", name: "Belarusian" },
  { lang: "bem", name: "Bemba" },
  { lang: "bew", name: "Betawi" },
  { lang: "bg", name: "Bulgarian" },
  { lang: "bho", name: "Bhojpuri" },
  { lang: "bik", name: "Bikol" },
  { lang: "bm", name: "Bambara" },
  { lang: "bn", name: "Bengali" },
  { lang: "br", name: "Breton" },
  { lang: "bs", name: "Bosnian" },
  { lang: "bts", name: "Batak Simalungun" },
  { lang: "btx", name: "Batak Karo" },
  { lang: "bua", name: "Buriat" },
  { lang: "ca", name: "Catalan" },
  { lang: "ceb", name: "Cebuano" },
  { lang: "cgg", name: "Chiga" },
  { lang: "chm", name: "Mari" },
  { lang: "ckb", name: "Central Kurdish" },
  { lang: "cnh", name: "Haka Chin" },
  { lang: "co", name: "Corsican" },
  { lang: "crh", name: "Crimean Tatar" },
  { lang: "crs", name: "Seselwa Creole French" },
  { lang: "cs", name: "Czech" },
  { lang: "cv", name: "Chuvash" },
  { lang: "cy", name: "Welsh" },
  { lang: "da", name: "Danish" },
  { lang: "de", name: "German" },
  { lang: "din", name: "Dinka" },
  { lang: "doi", name: "Dogri" },
  { lang: "dov", name: "Dombe" },
  { lang: "dv", name: "Dhivehi" },
  { lang: "dz", name: "Dzongkha" },
  { lang: "ee", name: "Ewe" },
  { lang: "el", name: "Modern Greek" },
  { lang: "en", name: "English" },
  { lang: "en-UK", name: "English (United Kingdom)" },
  { lang: "en-US", name: "English (United States)" },
  { lang: "eo", name: "Esperanto" },
  { lang: "es", name: "Spanish" },
  { lang: "et", name: "Estonian" },
  { lang: "eu", name: "Basque" },
  { lang: "fa", name: "Persian" },
  { lang: "ff", name: "Fulah" },
  { lang: "fi", name: "Finnish" },
  { lang: "fj", name: "Fijian" },
  { lang: "fr", name: "French" },
  { lang: "fr-CA", name: "French (Canada)" },
  { lang: "fy", name: "Western Frisian" },
  { lang: "ga", name: "Irish" },
  { lang: "gaa", name: "Ga" },
  { lang: "gd", name: "Scottish Gaelic" },
  { lang: "gl", name: "Galician" },
  { lang: "gn", name: "Guarani" },
  { lang: "gom", name: "Goan Konkani" },
  { lang: "gu", name: "Gujarati" },
  { lang: "ha", name: "Hausa" },
  { lang: "haw", name: "Hawaiian" },
  { lang: "he", name: "Hebrew" },
  { lang: "hi", name: "Hindi" },
  { lang: "hil", name: "Hiligaynon" },
  { lang: "hmn", name: "Hmong" },
  { lang: "hr", name: "Croatian" },
  { lang: "hrx", name: "Hunsrik" },
  { lang: "ht", name: "Haitian" },
  { lang: "hu", name: "Hungarian" },
  { lang: "hy", name: "Armenian" },
  { lang: "id", name: "Indonesian" },
  { lang: "ig", name: "Igbo" },
  { lang: "ilo", name: "Iloko" },
  { lang: "is", name: "Icelandic" },
  { lang: "it", name: "Italian" },
  { lang: "iw", name: "Hebrew" },
  { lang: "ja", name: "Japanese" },
  { lang: "jv", name: "Javanese" },
  { lang: "jw", name: "Javanese" },
  { lang: "ka", name: "Georgian" },
  { lang: "kk", name: "Kazakh" },
  { lang: "km", name: "Central Khmer" },
  { lang: "kn", name: "Kannada" },
  { lang: "ko", name: "Korean" },
  { lang: "kri", name: "Krio" },
  { lang: "ktu", name: "Kituba (Democratic Republic of Congo)" },
  { lang: "ku", name: "Kurdish" },
  { lang: "ky", name: "Kirghiz" },
  { lang: "la", name: "Latin" },
  { lang: "lb", name: "Luxembourgish" },
  { lang: "lg", name: "Ganda" },
  { lang: "li", name: "Limburgan" },
  { lang: "lij", name: "Ligurian" },
  { lang: "lmo", name: "Lombard" },
  { lang: "ln", name: "Lingala" },
  { lang: "lo", name: "Lao" },
  { lang: "lt", name: "Lithuanian" },
  { lang: "ltg", name: "Latgalian" },
  { lang: "luo", name: "Luo" },
  { lang: "lus", name: "Lushai" },
  { lang: "lv", name: "Latvian" },
  { lang: "mai", name: "Maithili" },
  { lang: "mak", name: "Makasar" },
  { lang: "mg", name: "Malagasy" },
  { lang: "mi", name: "Maori" },
  { lang: "min", name: "Minangkabau" },
  { lang: "mk", name: "Macedonian" },
  { lang: "ml", name: "Malayalam" },
  { lang: "mn", name: "Mongolian" },
  { lang: "mni-Mtei", name: "Meitei" },
  { lang: "mr", name: "Marathi" },
  { lang: "ms", name: "Malay" },
  { lang: "ms-Arab", name: "Malay (Arabic)" },
  { lang: "mt", name: "Maltese" },
  { lang: "my", name: "Burmese" },
  { lang: "ne", name: "Nepali" },
  { lang: "new", name: "Newari" },
  { lang: "nl", name: "Dutch" },
  { lang: "no", name: "Norwegian" },
  { lang: "nr", name: "South Ndebele" },
  { lang: "nso", name: "Pedi" },
  { lang: "nus", name: "Nuer" },
  { lang: "ny", name: "Nyanja" },
  { lang: "oc", name: "Occitan" },
  { lang: "om", name: "Oromo" },
  { lang: "or", name: "Oriya" },
  { lang: "pa", name: "Panjabi" },
  { lang: "pa-Arab", name: "Panjabi (Arabic)" },
  { lang: "pag", name: "Pangasinan" },
  { lang: "pam", name: "Pampanga" },
  { lang: "pap", name: "Papiamento" },
  { lang: "pl", name: "Polish" },
  { lang: "ps", name: "Pushto" },
  { lang: "pt", name: "Portuguese" },
  { lang: "pt-PT", name: "Portuguese (Portugal)" },
  { lang: "qu", name: "Quechua" },
  { lang: "rn", name: "Rundi" },
  { lang: "ro", name: "Romanian" },
  { lang: "rom", name: "Romany" },
  { lang: "ru", name: "Russian" },
  { lang: "rw", name: "Kinyarwanda" },
  { lang: "sa", name: "Sanskrit" },
  { lang: "scn", name: "Sicilian" },
  { lang: "sd", name: "Sindhi" },
  { lang: "sg", name: "Sango" },
  { lang: "shn", name: "Shan" },
  { lang: "si", name: "Sinhala" },
  { lang: "sk", name: "Slovak" },
  { lang: "sl", name: "Slovenian" },
  { lang: "sm", name: "Samoan" },
  { lang: "sn", name: "Shona" },
  { lang: "so", name: "Somali" },
  { lang: "sq", name: "Albanian" },
  { lang: "sr", name: "Serbian" },
  { lang: "ss", name: "Swati" },
  { lang: "st", name: "Southern Sotho" },
  { lang: "su", name: "Sundanese" },
  { lang: "sv", name: "Swedish" },
  { lang: "sw", name: "Swahili" },
  { lang: "szl", name: "Silesian" },
  { lang: "ta", name: "Tamil" },
  { lang: "te", name: "Telugu" },
  { lang: "tet", name: "Tetum" },
  { lang: "tg", name: "Tajik" },
  { lang: "th", name: "Thai" },
  { lang: "ti", name: "Tigrinya" },
  { lang: "tk", name: "Turkmen" },
  { lang: "tl", name: "Tagalog" },
  { lang: "tn", name: "Tswana" },
  { lang: "tr", name: "Turkish" },
  { lang: "ts", name: "Tsonga" },
  { lang: "tt", name: "Tatar" },
  { lang: "ug", name: "Uighur" },
  { lang: "uk", name: "Ukrainian" },
  { lang: "ur", name: "Urdu" },
  { lang: "uz", name: "Uzbek" },
  { lang: "vi", name: "Vietnamese" },
  { lang: "xh", name: "Xhosa" },
  { lang: "yi", name: "Yiddish" },
  { lang: "yo", name: "Yoruba" },
  { lang: "yua", name: "Yucatec Maya" },
  { lang: "yue", name: "Yue Chinese" },
  { lang: "zh", name: "Chinese" },
  { lang: "zh-Hans", name: "Chinese (Simplified)" },
  { lang: "zh-Hant", name: "Chinese (Traditional)" },
  { lang: "zu", name: "Zulu" },
];