import type LangCodeRecord from "./LangCodeRecord"

export const commonLangs: Array<LangCodeRecord> = [
  {lang: "ar", name: "Arabic"},
  {lang: "bg", name: "Bulgarian"},
  {lang: "cs", name: "Czech"},
  {lang: "da", name: "Danish"},
  {lang: "de", name: "German"},
  {lang: "el", name: "Greek"},
  {lang: "en", name: "English"},
  {lang: "es", name: "Spanish"},
  {lang: "et", name: "Estonian"},
  {lang: "fi", name: "Finnish"},
  {lang: "fr", name: "French"},
  {lang: "he", name: "Hebrew"},
  {lang: "hu", name: "Hungarian"},
  {lang: "id", name: "Indonesian"},
  {lang: "it", name: "Italian"},
  {lang: "ja", name: "Japanese"},
  {lang: "ko", name: "Korean"},
  {lang: "lt", name: "Lithuanian"},
  {lang: "lv", name: "Latvian"},
  {lang: "nb", name: "Norwegian"},
  {lang: "nl", name: "Dutch"},
  {lang: "pl", name: "Polish"},
  {lang: "pt", name: "Portuguese"},
  {lang: "ro", name: "Romanian"},
  {lang: "ru", name: "Russian"},
  {lang: "sk", name: "Slovak"},
  {lang: "sl", name: "Slovenian"},
  {lang: "sv", name: "Swedish"},
  {lang: "th", name: "Thai"},
  {lang: "tr", name: "Turkish"},
  {lang: "uk", name: "Ukrainian"},
  {lang: "vi", name: "Vietnamese"},
  {lang: "zh", name: "Chinese"}
];